alias dev="bun dev"
alias install="bun install"
alias pipeline="open https://app.netlify.com/sites/voluble-capybara-20920e/deploys"
alias gp="git push"
alias gpp="git push && sleep 1 && pipeline"
alias prod="open https://main--voluble-capybara-20920e.netlify.app"
alias csdoc="open https://www.contentstack.com/docs/developers/sdks/content-delivery-sdk/javascript-browser/reference"